# fly.toml app configuration file generated for ukraine-o-event-fe on 2023-09-25T15:15:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ukraine-o-event-fe"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
